In [2]:
import numpy as np
import csv



<type 'numpy.ndarray'>


(2, 97)


In [11]:
def univariateXfetcher():
    mylist = []
    with open("ex1data1.txt") as csvfile:
        reader = csv.reader(csvfile)
        mylist = list(reader)
    
    data = np.array(mylist,dtype='float64')
    x,y = data.T
   
    x = x.reshape(97)
    onesvector = np.ones(97)

    X = np.empty([2,97])
    X[0] = onesvector
    X[1] = x
    return X,y


        

In [64]:
theta = np.empty ([1,2])
X,y = univariateXfetcher()
y = y.reshape(97)
m = X.shape[1]

i = 0
while i < 5000 :
    
    hyp = np.dot(theta,X)
    hyp = hyp.reshape(97)
    diff = np.subtract(hyp,y)
    diff = diff.reshape(1,97)
    core = np.dot(diff,X.T)/m   
    core = core * 0.01
    theta = theta - core
    i+=1
    cost = np.sum(np.square(diff))/(2*m)
    print cost
    
print theta


32.0727338775
6.73719046487
5.9315935686
5.90115470708
5.89522858644
5.89009494312
5.88500415844
5.87993248049
5.87487909476
5.86984391181
5.86482686531
5.85982788993
5.85484692057
5.84988389238
5.84493874072
5.84001140122
5.83510180971
5.83020990226
5.82533561518
5.82047888501
5.81563964849
5.81081784263
5.80601340463
5.80122627194
5.79645638223
5.79170367338
5.78696808352
5.78224955098
5.77754801432
5.77286341232
5.76819568399
5.76354476855
5.75891060543
5.75429313431
5.74969229505
5.74510802775
5.74054027271
5.73598897046
5.73145406174
5.7269354875
5.72243318891
5.71794710733
5.71347718436
5.7090233618
5.70458558165
5.70016378612
5.69575791765
5.69136791886
5.6869937326
5.6826353019
5.67829257002
5.6739654804
5.66965397671
5.66535800282
5.66107750277
5.65681242083
5.65256270148
5.64832828936
5.64410912936
5.63990516653
5.63571634612
5.63154261361
5.62738391464
5.62324019507
5.61911140093
5.61499747847
5.61089837413
5.60681403452
5.60274440646
5.59868943698
5.59464907325
5.5906232626

[[ 3.3939595]] 17.592


array([ 1.    ,  6.1101])

array([[-3.89530051,  1.19298539]])

[[ 1.      6.1101]
 [ 1.      5.5277]
 [ 1.      8.5186]
 [ 1.      7.0032]
 [ 1.      5.8598]] [ 17.592    9.1302  13.662   11.854    6.8233]


13.662000000000001