In [2]:
import numpy as np

#Find indices of non-zero elements from [1,2,0,0,4,0]


a = np.array([1,2,0,0,4,0])

a = np.array(np.nonzero(a))
a.T


array([[0],
       [1],
       [4]])

In [22]:
#Create a null vector of size 10

np.zeros( (1,5) )


[[ 0.  0.  0.  0.  0.]]


In [26]:
#Create a null vector of size 10 but the fifth value which is 1

a = np.zeros ( (10) )
a[4] = 1

print a


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [29]:
#Create a vector with values ranging from 10 to 49 

np.arange(10,50)



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [32]:
#Create a 3x3 matrix with values ranging from 0 to 8 

np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
#Create a 3x3 identity matrix

np.ones( (3,3) )


(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


In [45]:
#Create a 3x3x3 array with random values

np.random.random( (3,3) ) 


array([[ 0.99161261,  0.06479506,  0.59173784],
       [ 0.89303665,  0.72482402,  0.35686421],
       [ 0.56709305,  0.66935768,  0.60515455]])

In [64]:
#Create a 10x10 array with random values and find the minimum and maximum values

a = np.random.random( (3,3) )
print a

indices = np.where(a == a.max())
print indices

indices = np.where(a == a.min())
print indices


[[ 0.00406295  0.30765356  0.01457154]
 [ 0.29088911  0.09168934  0.41267657]
 [ 0.02713191  0.54668689  0.55027518]]
(array([2]), array([2]))
(array([0]), array([0]))


In [70]:
#Create a random vector of size 30 and find the mean value

a = np.random.random (30)
np.average(a)

0.47633442570512585

In [8]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element ?

a = np.arange(6*7*8).reshape(6,7,8)
print a
b= a.ravel()

element = b[100]
print element

np.where(a == element)



[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

(array([1]), array([5]), array([4]))

In [22]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

a=np.arange(5*3).reshape(5,3)
b=np.arange(3*2).reshape(3,2)

np.dot(a,b)


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [ ]:
#Normalize a 5x5 random matrix

a = np.arange(5*5).reshape(5,5)
print a
a = a/float(a.max())

print a


In [28]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.

a = np.arange(10)
a[4:8]=-a[4:8]
print a


[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [32]:
#Create a 5x5 matrix with row values ranging from 0 to 4 

a = np.random.random((5,5)) 

print a


[[ 0.27583571  0.17512141  0.0826211   0.09765212  0.98722143]
 [ 0.63200408  0.2080269   0.29511362  0.48597946  0.20410946]
 [ 0.2716503   0.44398979  0.17088921  0.46358616  0.71628567]
 [ 0.0905346   0.36466396  0.17980404  0.95746562  0.73816128]
 [ 0.10660829  0.48045542  0.70757203  0.06602742  0.55035035]]
